export const patents = [
  {
    title: "Filtering Spurious Knowledge Graph Relationships Between Labeled Entities",
    number: "US11755843B2",
    country: "US",
    inventors: "Nandana Mihindukulasooriya, Robert G. Farrell, Nicolas Rodolfo Fauceglia, Alfio Massimiliano Gliozzo",
    assignee: "International Business Machines Corporation",
    priority: "2019-10-14",
    filed: "2021-05-18",
    granted: "2023-09-12",
    published: "2023-09-12",
    summary: "Systems and techniques facilitate spurious relationship filtration from external knowledge graphs based on distributional semantics of an input corpus. A context component generates context-based word embeddings for terms and uses them to identify relationships that are likely to be spurious. The approach supports more reliable knowledge graph construction and downstream reasoning.",
    href: "https://patents.google.com/patent/US11755843B2/en"
  },
  {
    title: "Implementing Relation Linking for Knowledge Bases",
    number: "US12106230B2",
    country: "US",
    inventors: "Nandana Mihindukulasooriya, Gaetano Rossiello, Alfio Massimiliano Gliozzo, Pavan Kapanipathi Bangalore, Salim Roukos",
    assignee: "International Business Machines Corporation",
    priority: "2020-10-23",
    filed: "2020-10-23",
    granted: "2024-10-01",
    published: "2024-10-01",
    summary: "A system for relation linking over knowledge bases, including techniques for semantic parsing and linking relations in natural language questions to relations in a target knowledge base. The method identifies a natural language query, translates it into an intermediate representation, converts it into query triples, and links those relations to knowledge base triples.",
    href: "https://patents.google.com/patent/US12106230B2/en"
  },
  {
    title: "Canonicalization of Data Within Open Knowledge Graphs",
    number: "US20230087667A1",
    country: "US",
    inventors: "Sarthak Dash, Gaetano Rossiello, Nandana Mihindukulasooriya, Sugato Bagchi, Alfio Massimiliano Gliozzo",
    assignee: "International Business Machines Corporation",
    priority: "2021-09-21",
    filed: "2021-09-21",
    published: "2023-03-23",
    summary: "Embodiments provide computer-implemented methods, computer program products, and computer systems that learn entity representations and cluster assignments in response to receiving information. The techniques canonicalize noun phrases and relation phrases within open knowledge graphs, helping reduce redundant information and improve downstream search, linking, and natural language processing tasks.",
    href: "https://patents.google.com/patent/US20230087667A1/en"
  },
  {
    title: "Knowledge Base Question Answering",
    number: "US11868716B2",
    country: "US",
    inventors: "Srinivas Ravishankar, Pavan Kapanipathi Bangalore, Ibrahim Abdelaziz, Nandana Mihindukulasooriya, Dinesh Garg, Salim Roukos, Alexander Gray",
    assignee: "International Business Machines Corporation",
    priority: "2021-08-31",
    filed: "2021-08-31",
    granted: "2024-01-09",
    published: "2024-01-09",
    summary: "Computer processors parse a received natural language question into an abstract meaning representation graph, enrich it into an extended graph, and transform it into a query for knowledge base question answering. The system generates query graphs using a path-based approach and applies neuro-symbolic reasoning to produce answers from knowledge base facts.",
    href: "https://patents.google.com/patent/US11868716B2/en"
  },
  {
    title: "System, Computer-Implementation Method, and Computer Program for Generative Relation Linking",
    number: "JP2023011524A",
    country: "JP",
    inventors: "Nandana Mihindukulasooriya, Gaetano Rossiello, Alfio Massimiliano Gliozzo, Pavan Kapanipathi Bangalore, Salim Roukos",
    assignee: "International Business Machines Corporation",
    priority: "2021-07-12",
    filed: "2022-07-08",
    published: "2023-01-24",
    summary: "A system, device, computer-implemented method, or computer program that facilitates generative relational coupling for question answering on a knowledge base.",
    href: "https://patents.google.com/patent/JP2023011524A/en"
  },
  {
    title: "Keyphrase Generation Leveraging Public Repository Categories",
    number: "US12072841B2",
    country: "US",
    inventors: "Gaetano Rossiello, Md Faisal Mahbub Chowdhury, Alfio Massimiliano Gliozzo, Nandana Mihindukulasooriya, Michael Robert Glass",
    assignee: "International Business Machines Corporation",
    priority: "2022-11-14",
    filed: "2022-11-14",
    granted: "2024-08-27",
    published: "2024-08-27",
    summary: "A process for generating classifications of files to allow for file system organization or query augmentation using public repository categories and learned representations. The system generates keyphrases from an input document, calculates relevance scores, and balances relevance with diversity to produce useful file classifications.",
    href: "https://patents.google.com/patent/US12072841B2/en"
  },
  {
    title: "Generating Semantic Triplets from Unstructured Text",
    number: "US20240202447A1",
    country: "US",
    inventors: "Gaetano Rossiello, Alfio Massimiliano Gliozzo, Nandana Sampath Mihindukulasooriya, Md Faisal Mahbub Chowdhury, Michael Robert Glass",
    assignee: "International Business Machines Corporation",
    priority: "2022-12-14",
    filed: "2022-12-14",
    published: "2024-06-20",
    summary: "An embodiment generates a training dataset by aligning text from a document database with a named entity from a knowledge base, then enhances the dataset with named entity types and labels. A trained natural language processing model identifies entities in unstructured text and generates semantic triplets that connect them to related entities in a knowledge graph.",
    href: "https://patents.google.com/patent/US20240202447A1/en"
  },
  {
    title: "Artificial Intelligence Based Metadata Semantic Enrichment",
    number: "US12547837B2",
    country: "US",
    inventors: "Md Faisal Mahbub Chowdhury, Alfio Massimiliano Gliozzo, Nandana Sampath Mihindukulasooriya, Michael Robert Glass, Sarthak Dash, Sugato Bagchi, Gaetano Rossiello",
    assignee: "International Business Machines Corporation",
    priority: "2024-01-10",
    filed: "2024-01-10",
    granted: "2026-02-10",
    published: "2026-02-10",
    summary: "Mechanisms automatically generate semantically enhanced metadata for structured data using multi-task machine learning across multiple semantic metadata enhancement tasks. The approach fine-tunes a foundation model to generate table captions, column descriptions, data types, tags, and other metadata while using only the structure of the data, helping preserve privacy and improve downstream AI operations.",
    href: "https://patents.google.com/patent/US12547837B2/en"
  },
  {
    title: "Automated Evaluation of Information Retrieval",
    number: "US20220083559A1",
    country: "US",
    inventors: "Md Faisal Mahbub Chowdhury, Yu Deng, Alfio Massimiliano Gliozzo, Ruchi Mahindru, Nandana Mihindukulasooriya, Nicolas Rodolfo Fauceglia, Gaetano Rossiello",
    assignee: "International Business Machines Corporation",
    priority: "2020-09-16",
    filed: "2020-09-16",
    published: "2022-03-17",
    summary: "A method, system, and computer program product for automated evaluation of information retrieval systems using natural language queries associated with query difficulty levels. The system generates responses, feedback cues, and search results, then evaluates the retrieval system using query facets and simulated user behavior.",
    href: "https://patents.google.com/patent/US20220083559A1/en"
  },
  {
    title: "Discovering Ranked Domain Relevant Terms Using Knowledge",
    number: "US20210326636A1",
    country: "US",
    inventors: "Nandana Mihindukulasooriya, Ruchi Mahindru, Md Faisal Mahbub Chowdhury, Yu Deng, Alfio Massimiliano Gliozzo, Sarthak Dash, Nicolas Rodolfo Fauceglia, Gaetano Rossiello",
    assignee: "International Business Machines Corporation",
    priority: "2020-04-16",
    filed: "2020-04-16",
    published: "2021-10-21",
    summary: "A method for terminology ranking in natural language processing that receives terms extracted from a corpus and ranks them based on frequencies and domain knowledge. The system scores domain-relevant terms using knowledge graph relations and ontology information, enabling improved terminology discovery and knowledge graph construction.",
    href: "https://patents.google.com/patent/US20210326636A1/en"
  },
  {
    title: "Semantically Parsed Knowledge Base Question Answering Generalization",
    number: "US20240078443A1",
    country: "US",
    inventors: "Srinivas Ravishankar, Dung Ngoc Thai, Ibrahim Abdelaziz, Pavan Kapanipathi Bangalore, Tahira Naseem, Achille Belly Fokoue-Nkoutche, Nandana Mihindukulasooriya",
    assignee: "International Business Machines Corporation",
    priority: "2022-09-07",
    filed: "2022-09-07",
    published: "2024-03-07",
    summary: "Computer processors improve knowledge base question answering model convergence and prediction performance by generalizing the model based on transfer learning. The approach separates semantic parsing from knowledge base interaction, enabling zero-shot transfer across different knowledge graphs and improved performance in low-resource settings.",
    href: "https://patents.google.com/patent/US20240078443A1/en"
  },
  {
    title: "Permutation Invariance for Representing Linearized Tabular Data",
    number: "US20230409806A1",
    country: "US",
    inventors: "Sarthak Dash, Sugato Bagchi, Nandana Mihindukulasooriya, Alfio Massimiliano Gliozzo",
    assignee: "International Business Machines Corporation",
    priority: "2022-06-17",
    filed: "2022-06-17",
    published: "2023-12-21",
    summary: "An embodiment encodes permutation-invariant representations of linearized tabular data by assigning position identifiers to elements of a column or row. The representation preserves the meaning of tabular data when rows and columns are reordered, supporting improved table search, interpretation, question answering, and column annotation.",
    href: "https://patents.google.com/patent/US20230409806A1/en"
  },
  {
    title: "Knowledge Induction Using Corpus Expansion",
    number: "US20220067539A1",
    country: "US",
    inventors: "Nandana Mihindukulasooriya, Md Faisal Mahbub Chowdhury, Yu Deng, Ruchi Mahindru, Nicolas Rodolfo Fauceglia, Alfio Massimiliano Gliozzo",
    assignee: "International Business Machines Corporation",
    priority: "2020-09-01",
    filed: "2020-09-01",
    published: "2022-03-03",
    summary: "A method, computer program product, and computer system induce knowledge from a knowledge graph by determining a domain, a corresponding corpus, and corpus quality. When the corpus does not meet a quality threshold, the system selects candidate expansion corpora and documents, creates an expanded corpus, and generates a more comprehensive knowledge graph.",
    href: "https://patents.google.com/patent/US20220067539A1/en"
  },
  {
    title: "Linking Tabular Columns to Unseen Ontologies",
    number: "US12216635B2",
    country: "US",
    inventors: "Sarthak Dash, Sugato Bagchi, Nandana Sampath Mihindukulasooriya, Alfio Massimiliano Gliozzo",
    assignee: "International Business Machines Corporation",
    priority: "2023-06-06",
    filed: "2023-06-06",
    granted: "2025-02-04",
    published: "2025-02-04",
    summary: "An embodiment improves linking of tabular columns to column types in an ontology unseen during training using permutation-invariant representations of tabular data. The system encodes table columns, table headers, and target ontology types independently, using auxiliary glossary and taxonomy information to support zero-shot column linking.",
    href: "https://patents.google.com/patent/US12216635B2/en"
  },
  {
    title: "Noise Detection in Knowledge Graphs",
    number: "US11693896B2",
    country: "US",
    inventors: "Nandana Sampath Mihindukulasooriya, Oktie Hassanzadeh, Alfio Massimiliano Gliozzo, Sarthak Dash",
    assignee: "International Business Machines Corporation",
    priority: "2018-09-25",
    filed: "2018-09-25",
    granted: "2023-07-04",
    published: "2023-07-04",
    summary: "Techniques for autonomous classification and identification of different types of noise within a knowledge graph using computer-executable components. The system can identify inconsistent, generic, and factually false noise generated by information extraction processes, supporting comprehensive knowledge graph quality improvement.",
    href: "https://patents.google.com/patent/US11693896B2/en"
  },
  {
    title: "Keyphrase Generation",
    number: "US12436988B2",
    country: "US",
    inventors: "Md Faisal Mahbub Chowdhury, Alfio Massimiliano Gliozzo, Gaetano Rossiello, Michael Robert Glass, Nandana Sampath Mihindukulasooriya",
    assignee: "International Business Machines Corporation",
    priority: "2022-11-14",
    filed: "2022-11-14",
    granted: "2025-10-07",
    published: "2025-10-07",
    summary: "Using a trained keyphrase generation model, a set of keyphrases corresponding to an input document is generated and scored according to similarity between each keyphrase and the document. A diversity balancing function adjusts the scores to avoid redundant phrases and produce a more useful set of keyphrases for document analysis and classification.",
    href: "https://patents.google.com/patent/US12436988B2/en"
  }
];
